#!/usr/bin/env python3
"""KARL Prometheus Metrics Exporter.

Serves KARL metrics on /metrics for Prometheus scraping.
Reads from karl_status.json (generated by generate_status.py).

Usage:
    python3 metrics_exporter.py           # Start on port 9300
    python3 metrics_exporter.py --port 9301
    python3 metrics_exporter.py --once     # Print metrics to stdout and exit
"""

import json
import sys
import time
from http.server import HTTPServer, BaseHTTPRequestHandler
from pathlib import Path

KARL_DIR = Path(__file__).parent
STATUS_FILE = KARL_DIR / "karl_status.json"
TRAJECTORY_FILE = KARL_DIR / "trajectories.jsonl"
SHADOW_FILE = KARL_DIR / "routing_shadow.jsonl"

DEFAULT_PORT = 9300


def _count_lines(path):
    if not path.exists():
        return 0
    with open(path) as f:
        return sum(1 for _ in f)


def generate_metrics():
    """Generate Prometheus-format metrics from KARL status."""
    lines = []

    def gauge(name, help_text, value, labels=None):
        lines.append(f"# HELP {name} {help_text}")
        lines.append(f"# TYPE {name} gauge")
        label_str = ""
        if labels:
            label_str = "{" + ",".join(f'{k}="{v}"' for k, v in labels.items()) + "}"
        lines.append(f"{name}{label_str} {value}")

    # Load status
    status = {}
    if STATUS_FILE.exists():
        try:
            status = json.loads(STATUS_FILE.read_text())
        except (json.JSONDecodeError, OSError):
            pass

    # Live file counts (more accurate than cached status)
    traj_count = _count_lines(TRAJECTORY_FILE)
    shadow_count = _count_lines(SHADOW_FILE)

    gauge("karl_trajectories_total", "Total trajectory records", traj_count)
    gauge("karl_shadow_records_total", "Total shadow routing records", shadow_count)

    # From status JSON
    health = status.get("health", {})
    gauge("karl_scored_trajectories", "Scored trajectory count", health.get("scored_trajectories", 0))

    shadow = status.get("shadow", {})
    gauge("karl_shadow_hit_rate", "Shadow cache hit rate", shadow.get("hit_rate", 0))
    gauge("karl_shadow_vector_coverage", "Vector routing coverage", shadow.get("vector_coverage", 0))
    gauge("karl_shadow_avg_elapsed_ms", "Average shadow routing latency ms", shadow.get("avg_elapsed_ms", 0))

    accuracy = status.get("accuracy", {})
    if accuracy.get("vector_accuracy") is not None:
        gauge("karl_vector_accuracy", "Vector routing accuracy vs actual skill", accuracy["vector_accuracy"])
    if accuracy.get("regex_accuracy") is not None:
        gauge("karl_regex_accuracy", "Regex routing accuracy vs actual skill", accuracy["regex_accuracy"])
    gauge("karl_annotated_records", "Shadow records annotated with actual skill", accuracy.get("annotated", 0))
    if accuracy.get("top3_accuracy") is not None:
        gauge("karl_vector_top3_accuracy", "Top-3 hit rate for vector routing", accuracy["top3_accuracy"])
    if accuracy.get("mrr") is not None:
        gauge("karl_vector_mrr", "Mean Reciprocal Rank for vector routing", accuracy["mrr"])
    if accuracy.get("reward_weighted_accuracy") is not None:
        gauge("karl_reward_weighted_accuracy", "Reward-weighted vector accuracy", accuracy["reward_weighted_accuracy"])

    latency = status.get("latency", {})
    if latency.get("p50_ms") is not None:
        gauge("karl_embed_latency_p50_ms", "Embed p50 latency ms", latency["p50_ms"])
    if latency.get("p95_ms") is not None:
        gauge("karl_embed_latency_p95_ms", "Embed p95 latency ms", latency["p95_ms"])

    reward = status.get("reward_stats", {})
    if reward.get("mean") is not None:
        gauge("karl_reward_mean", "Mean reward score", reward["mean"])
    gauge("karl_reward_scored", "Number of scored trajectories", reward.get("scored", 0))

    # Per-domain rewards
    for domain, dstats in reward.get("by_domain", {}).items():
        if isinstance(dstats, dict) and dstats.get("mean") is not None:
            gauge("karl_domain_reward_mean", "Per-domain reward mean",
                  dstats["mean"], {"domain": domain})
            gauge("karl_domain_trajectories", "Per-domain trajectory count",
                  dstats.get("count", 0), {"domain": domain})

    promotion = status.get("promotion", {})
    gauge("karl_promotion_ready", "Whether promotion gate is ready", 1 if promotion.get("ready") else 0)

    # Read config.json directly for freshest routing mode
    config_data = status.get("config", {})
    config_path = KARL_DIR / "config.json"
    if config_path.exists():
        try:
            config_data = json.loads(config_path.read_text())
        except (json.JSONDecodeError, OSError):
            pass
    gauge("karl_routing_mode", "Current routing mode (0=shadow, 1=active)",
          1 if config_data.get("routing_mode") == "active" else 0)

    # Embedding model info metric
    embed_cfg = status.get("embedding", {})
    if embed_cfg.get("model"):
        lines.append("# HELP karl_embedding_info Embedding model info")
        lines.append("# TYPE karl_embedding_info gauge")
        labels = {
            "model": embed_cfg.get("model", "unknown"),
            "dimension": str(embed_cfg.get("dimension", 0)),
        }
        label_str = "{" + ",".join(f'{k}="{v}"' for k, v in labels.items()) + "}"
        lines.append(f"karl_embedding_info{label_str} 1")
    embed_cache = status.get("embedding", {})
    gauge("karl_embedding_cache_entries", "Prompt embedding cache entries",
          embed_cache.get("cache_entries", 0))
    gauge("karl_skill_centroids_loaded", "Number of skill centroids loaded",
          embed_cache.get("skill_centroids", 0))

    # Centroid health
    cdiv = embed_cache.get("centroid_diversity", {})
    if cdiv.get("avg_similarity") is not None:
        gauge("karl_centroid_avg_similarity", "Average pairwise centroid similarity",
              cdiv["avg_similarity"])
    if cdiv.get("max_similarity") is not None:
        gauge("karl_centroid_max_similarity", "Maximum pairwise centroid similarity",
              cdiv["max_similarity"])
    health_map = {"good": 2, "warning": 1, "poor": 0}
    if cdiv.get("health") in health_map:
        gauge("karl_centroid_health", "Centroid health (0=poor 1=warning 2=good)",
              health_map[cdiv["health"]])
    gauge("karl_centroid_clustered_skills", "Number of poorly-separated skill centroids",
          len(cdiv.get("clustered_skills", [])))
    gauge("karl_centroid_versions_total", "Total centroid version snapshots",
          embed_cache.get("centroid_versions", 0))

    trend = status.get("reward_trend", {})
    if trend.get("rolling_mean") is not None:
        gauge("karl_reward_rolling_7d_mean", "7-day rolling reward mean", trend["rolling_mean"])

    # Per-skill health
    for skill_name, sdata in health.get("skills", {}).items():
        if isinstance(sdata, dict):
            gauge("karl_skill_trajectories", "Per-skill trajectory count",
                  sdata.get("trajectories", 0), {"skill": skill_name})
            if sdata.get("mean_reward") is not None:
                gauge("karl_skill_reward_mean", "Per-skill mean reward",
                      sdata["mean_reward"], {"skill": skill_name})

    # Per-skill readiness
    skill_readiness = status.get("skill_readiness", {}).get("skills", {})
    for skill_name, sready in skill_readiness.items():
        if isinstance(sready, dict):
            ready = 1 if sready.get("ready") else 0
            gauge("karl_skill_ready", "Per-skill promotion readiness",
                  ready, {"skill": skill_name})

    # Hybrid routing
    hybrid = status.get("hybrid_routing", {})
    gauge("karl_hybrid_vector_skills", "Skills routed via vector in hybrid mode",
          hybrid.get("vector_count", 0))
    gauge("karl_hybrid_regex_skills", "Skills falling back to regex in hybrid mode",
          hybrid.get("regex_count", 0))

    # SFT readiness
    sft = status.get("sft", {}).get("readiness", {})
    gauge("karl_sft_ready", "Whether SFT training data is ready", 1 if sft.get("ready") else 0)
    gauge("karl_sft_exportable", "SFT-exportable trajectory count", sft.get("exportable", 0))
    gauge("karl_sft_high_quality", "High+medium quality trajectories for SFT",
          sft.get("high_quality_count", 0))
    gauge("karl_sft_distinct_skills", "Distinct skills in SFT data",
          sft.get("distinct_skills", 0))

    # Accuracy by source (computed live from shadow file)
    if SHADOW_FILE.exists():
        try:
            src_stats = {}
            with open(SHADOW_FILE) as f:
                for line in f:
                    try:
                        r = json.loads(line)
                        if not r.get("actual_skill") or not r.get("vector"):
                            continue
                        src = r.get("source", "live")
                        if src not in src_stats:
                            src_stats[src] = {"total": 0, "correct": 0}
                        src_stats[src]["total"] += 1
                        if r.get("vector_correct"):
                            src_stats[src]["correct"] += 1
                    except json.JSONDecodeError:
                        continue
            for src, ss in src_stats.items():
                gauge("karl_source_accuracy", "Vector accuracy by record source",
                      round(ss["correct"] / ss["total"], 4) if ss["total"] else 0,
                      {"source": src})
                gauge("karl_source_records", "Annotated record count by source",
                      ss["total"], {"source": src})
        except (OSError, IOError):
            pass

    # Skill coverage
    coverage = status.get("skill_coverage", {})
    gauge("karl_skill_coverage_pct", "Skill coverage percentage",
          coverage.get("coverage_pct", 0))

    # Promotion forecast
    forecast = status.get("promotion_forecast", {})
    if forecast.get("days_remaining") is not None:
        gauge("karl_promotion_days_remaining", "Estimated days to promotion",
              forecast["days_remaining"])
    gauge("karl_shadow_daily_rate", "Shadow records per day",
          forecast.get("daily_rate", 0))

    # Reward distribution histogram (computed from trajectories file)
    if TRAJECTORY_FILE.exists():
        buckets = [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1.0]
        counts = {b: 0 for b in buckets}
        counts[float("inf")] = 0
        total_reward = 0
        reward_count = 0
        try:
            with open(TRAJECTORY_FILE) as f:
                for line in f:
                    try:
                        r = json.loads(line)
                        score = r.get("outcome", {}).get("reward_score")
                        if score is not None:
                            reward_count += 1
                            total_reward += score
                            for b in buckets:
                                if score <= b:
                                    counts[b] += 1
                                    break
                            else:
                                counts[float("inf")] += 1
                    except json.JSONDecodeError:
                        continue

            if reward_count > 0:
                lines.append("# HELP karl_reward_distribution Reward score distribution")
                lines.append("# TYPE karl_reward_distribution histogram")
                cumulative = 0
                for b in buckets:
                    cumulative += counts[b]
                    lines.append(f'karl_reward_distribution_bucket{{le="{b}"}} {cumulative}')
                cumulative += counts[float("inf")]
                lines.append(f'karl_reward_distribution_bucket{{le="+Inf"}} {cumulative}')
                lines.append(f"karl_reward_distribution_sum {round(total_reward, 4)}")
                lines.append(f"karl_reward_distribution_count {reward_count}")
        except (OSError, IOError):
            pass

    # Quality grade distribution
    quality_dist = status.get("health", {}).get("quality_distribution", {})
    if quality_dist:
        for grade, count in quality_dist.items():
            gauge("karl_quality_grade", "Trajectory count per quality grade",
                  count, {"grade": grade})

    # Status file freshness
    if STATUS_FILE.exists():
        age_s = time.time() - STATUS_FILE.stat().st_mtime
        gauge("karl_status_age_seconds", "Age of karl_status.json in seconds", round(age_s, 1))

    return "\n".join(lines) + "\n"


def generate_health():
    """Generate JSON health check response."""
    health = {"status": "ok", "service": "karl-metrics-exporter", "port": DEFAULT_PORT}

    if STATUS_FILE.exists():
        age_s = time.time() - STATUS_FILE.stat().st_mtime
        health["status_age_seconds"] = round(age_s, 1)
        if age_s > 3600:
            health["status"] = "degraded"
            health["warning"] = "status file stale (>1h)"
    else:
        health["status"] = "degraded"
        health["warning"] = "no status file"

    health["trajectories"] = _count_lines(TRAJECTORY_FILE)
    health["shadow_records"] = _count_lines(SHADOW_FILE)
    return health


class MetricsHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/metrics":
            body = generate_metrics().encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/plain; version=0.0.4; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        elif self.path == "/health":
            body = json.dumps(generate_health()).encode()
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        elif self.path == "/status":
            # Serve full karl_status.json for dashboard consumption
            body = b"{}"
            if STATUS_FILE.exists():
                try:
                    body = STATUS_FILE.read_bytes()
                except OSError:
                    pass
            self.send_response(200)
            self.send_header("Content-Type", "application/json")
            self.send_header("Access-Control-Allow-Origin", "*")
            self.send_header("Content-Length", str(len(body)))
            self.end_headers()
            self.wfile.write(body)
        else:
            self.send_response(200)
            body = b"KARL Metrics Exporter. /metrics for Prometheus, /health for status.\n"
            self.send_header("Content-Type", "text/plain")
            self.end_headers()
            self.wfile.write(body)

    def log_message(self, format, *args):
        pass  # Suppress request logging


def main():
    if "--once" in sys.argv:
        print(generate_metrics())
        return

    port = DEFAULT_PORT
    for i, arg in enumerate(sys.argv):
        if arg == "--port" and i + 1 < len(sys.argv):
            port = int(sys.argv[i + 1])

    server = HTTPServer(("0.0.0.0", port), MetricsHandler)
    print(f"KARL metrics exporter running on :{port}/metrics")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        server.shutdown()


if __name__ == "__main__":
    main()
